//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DispatchPlatform.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DispatchPlatform.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_m_Ring {
            get {
                object obj = ResourceManager.GetObject("b_m_Ring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_MeetingMemberIsolate {
            get {
                object obj = ResourceManager.GetObject("b_MeetingMemberIsolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_MeetingMemberNoSpeek {
            get {
                object obj = ResourceManager.GetObject("b_MeetingMemberNoSpeek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_n_Busy {
            get {
                object obj = ResourceManager.GetObject("b_n_Busy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_n_Insert {
            get {
                object obj = ResourceManager.GetObject("b_n_Insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_n_Keep {
            get {
                object obj = ResourceManager.GetObject("b_n_Keep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_n_Listen {
            get {
                object obj = ResourceManager.GetObject("b_n_Listen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_n_OffLine {
            get {
                object obj = ResourceManager.GetObject("b_n_OffLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_n_OnLine {
            get {
                object obj = ResourceManager.GetObject("b_n_OnLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_n_Record {
            get {
                object obj = ResourceManager.GetObject("b_n_Record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigIconSet {
            get {
                object obj = ResourceManager.GetObject("BigIconSet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomBackground {
            get {
                object obj = ResourceManager.GetObject("BottomBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomBoxOffLine {
            get {
                object obj = ResourceManager.GetObject("BottomBoxOffLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomBoxOnLIne {
            get {
                object obj = ResourceManager.GetObject("BottomBoxOnLIne", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomDBOffLine {
            get {
                object obj = ResourceManager.GetObject("BottomDBOffLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BottomDBOnLine {
            get {
                object obj = ResourceManager.GetObject("BottomDBOnLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BoxOffline {
            get {
                object obj = ResourceManager.GetObject("BoxOffline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BoxOnline {
            get {
                object obj = ResourceManager.GetObject("BoxOnline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BroadcastingBack {
            get {
                object obj = ResourceManager.GetObject("BroadcastingBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BroadcastNorml {
            get {
                object obj = ResourceManager.GetObject("BroadcastNorml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BroadcastSelect {
            get {
                object obj = ResourceManager.GetObject("BroadcastSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnExit {
            get {
                object obj = ResourceManager.GetObject("btnExit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnLock {
            get {
                object obj = ResourceManager.GetObject("btnLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonBack {
            get {
                object obj = ResourceManager.GetObject("ButtonBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonNormal {
            get {
                object obj = ResourceManager.GetObject("ButtonNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonSelect {
            get {
                object obj = ResourceManager.GetObject("ButtonSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CallKeyborad {
            get {
                object obj = ResourceManager.GetObject("CallKeyborad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_0_normal {
            get {
                object obj = ResourceManager.GetObject("cb_0_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_0_on {
            get {
                object obj = ResourceManager.GetObject("cb_0_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_1_normal {
            get {
                object obj = ResourceManager.GetObject("cb_1_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_1_on {
            get {
                object obj = ResourceManager.GetObject("cb_1_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_2_normal {
            get {
                object obj = ResourceManager.GetObject("cb_2_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_2_on {
            get {
                object obj = ResourceManager.GetObject("cb_2_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_3_normal {
            get {
                object obj = ResourceManager.GetObject("cb_3_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_3_on {
            get {
                object obj = ResourceManager.GetObject("cb_3_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_4_normal {
            get {
                object obj = ResourceManager.GetObject("cb_4_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_4_on {
            get {
                object obj = ResourceManager.GetObject("cb_4_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_5_normal {
            get {
                object obj = ResourceManager.GetObject("cb_5_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_5_on {
            get {
                object obj = ResourceManager.GetObject("cb_5_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_6_normal {
            get {
                object obj = ResourceManager.GetObject("cb_6_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_6_on {
            get {
                object obj = ResourceManager.GetObject("cb_6_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_7_normal {
            get {
                object obj = ResourceManager.GetObject("cb_7_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_7_on {
            get {
                object obj = ResourceManager.GetObject("cb_7_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_8_normal {
            get {
                object obj = ResourceManager.GetObject("cb_8_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_8_on {
            get {
                object obj = ResourceManager.GetObject("cb_8_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_9_normal {
            get {
                object obj = ResourceManager.GetObject("cb_9_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_9_on {
            get {
                object obj = ResourceManager.GetObject("cb_9_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_call_Normal {
            get {
                object obj = ResourceManager.GetObject("cb_call_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_call_on {
            get {
                object obj = ResourceManager.GetObject("cb_call_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_Clear_normal {
            get {
                object obj = ResourceManager.GetObject("cb_Clear_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_clear_on {
            get {
                object obj = ResourceManager.GetObject("cb_clear_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_Close_normal {
            get {
                object obj = ResourceManager.GetObject("cb_Close_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_close_on {
            get {
                object obj = ResourceManager.GetObject("cb_close_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_handup_Normal {
            get {
                object obj = ResourceManager.GetObject("cb_handup_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_handup_on {
            get {
                object obj = ResourceManager.GetObject("cb_handup_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_jing_normal {
            get {
                object obj = ResourceManager.GetObject("cb_jing_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_jing_on {
            get {
                object obj = ResourceManager.GetObject("cb_jing_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_tran_Normal {
            get {
                object obj = ResourceManager.GetObject("cb_tran_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_tran_On {
            get {
                object obj = ResourceManager.GetObject("cb_tran_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_xing_normal {
            get {
                object obj = ResourceManager.GetObject("cb_xing_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_xing_on {
            get {
                object obj = ResourceManager.GetObject("cb_xing_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cencel {
            get {
                object obj = ResourceManager.GetObject("Cencel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommandBackGround {
            get {
                object obj = ResourceManager.GetObject("CommandBackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConfirmBroadcastBack {
            get {
                object obj = ResourceManager.GetObject("ConfirmBroadcastBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D_Busy {
            get {
                object obj = ResourceManager.GetObject("D_Busy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D_Hookon {
            get {
                object obj = ResourceManager.GetObject("D_Hookon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D_Keep {
            get {
                object obj = ResourceManager.GetObject("D_Keep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D_Listen {
            get {
                object obj = ResourceManager.GetObject("D_Listen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D_Offline {
            get {
                object obj = ResourceManager.GetObject("D_Offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D_Online {
            get {
                object obj = ResourceManager.GetObject("D_Online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D_Record {
            get {
                object obj = ResourceManager.GetObject("D_Record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D_Ring {
            get {
                object obj = ResourceManager.GetObject("D_Ring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DispatchNorml {
            get {
                object obj = ResourceManager.GetObject("DispatchNorml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DispatchSelect {
            get {
                object obj = ResourceManager.GetObject("DispatchSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExitIcon {
            get {
                object obj = ResourceManager.GetObject("ExitIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Flower {
            get {
                object obj = ResourceManager.GetObject("Flower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icoGroupCall {
            get {
                object obj = ResourceManager.GetObject("icoGroupCall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeepIco {
            get {
                object obj = ResourceManager.GetObject("KeepIco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Keyboradl {
            get {
                object obj = ResourceManager.GetObject("Keyboradl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeybordICO {
            get {
                object obj = ResourceManager.GetObject("KeybordICO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeybordNormal {
            get {
                object obj = ResourceManager.GetObject("KeybordNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeybordSlect {
            get {
                object obj = ResourceManager.GetObject("KeybordSlect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LemcBackground {
            get {
                object obj = ResourceManager.GetObject("LemcBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LemcButtonBackground {
            get {
                object obj = ResourceManager.GetObject("LemcButtonBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LemcWait {
            get {
                object obj = ResourceManager.GetObject("LemcWait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ListenIco {
            get {
                object obj = ResourceManager.GetObject("ListenIco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LockIcon {
            get {
                object obj = ResourceManager.GetObject("LockIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainBackGround {
            get {
                object obj = ResourceManager.GetObject("MainBackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainContentBackGround {
            get {
                object obj = ResourceManager.GetObject("MainContentBackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MainDispatchBackground {
            get {
                object obj = ResourceManager.GetObject("MainDispatchBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MeetingMemberIsolate {
            get {
                object obj = ResourceManager.GetObject("MeetingMemberIsolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MeetingMemberNoSpeek {
            get {
                object obj = ResourceManager.GetObject("MeetingMemberNoSpeek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MeetingNorml {
            get {
                object obj = ResourceManager.GetObject("MeetingNorml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MeetingSelect {
            get {
                object obj = ResourceManager.GetObject("MeetingSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MemberBackgound {
            get {
                object obj = ResourceManager.GetObject("MemberBackgound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MemberSlect {
            get {
                object obj = ResourceManager.GetObject("MemberSlect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_Busy {
            get {
                object obj = ResourceManager.GetObject("n_Busy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_Insert {
            get {
                object obj = ResourceManager.GetObject("n_Insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_Keep {
            get {
                object obj = ResourceManager.GetObject("n_Keep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_Listen {
            get {
                object obj = ResourceManager.GetObject("n_Listen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_OffLine {
            get {
                object obj = ResourceManager.GetObject("n_OffLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_OnLine {
            get {
                object obj = ResourceManager.GetObject("n_OnLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_Record {
            get {
                object obj = ResourceManager.GetObject("n_Record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap n_Ring {
            get {
                object obj = ResourceManager.GetObject("n_Ring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NormalWait {
            get {
                object obj = ResourceManager.GetObject("NormalWait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk__ {
            get {
                object obj = ResourceManager.GetObject("osk__", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_0 {
            get {
                object obj = ResourceManager.GetObject("osk_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_1 {
            get {
                object obj = ResourceManager.GetObject("osk_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_2 {
            get {
                object obj = ResourceManager.GetObject("osk_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_3 {
            get {
                object obj = ResourceManager.GetObject("osk_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_4 {
            get {
                object obj = ResourceManager.GetObject("osk_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_5 {
            get {
                object obj = ResourceManager.GetObject("osk_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_6 {
            get {
                object obj = ResourceManager.GetObject("osk_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_7 {
            get {
                object obj = ResourceManager.GetObject("osk_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_8 {
            get {
                object obj = ResourceManager.GetObject("osk_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_9 {
            get {
                object obj = ResourceManager.GetObject("osk_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_a {
            get {
                object obj = ResourceManager.GetObject("osk_a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_b {
            get {
                object obj = ResourceManager.GetObject("osk_b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_c {
            get {
                object obj = ResourceManager.GetObject("osk_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_d {
            get {
                object obj = ResourceManager.GetObject("osk_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_delete {
            get {
                object obj = ResourceManager.GetObject("osk_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_di {
            get {
                object obj = ResourceManager.GetObject("osk_di", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_dian {
            get {
                object obj = ResourceManager.GetObject("osk_dian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_e {
            get {
                object obj = ResourceManager.GetObject("osk_e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_f {
            get {
                object obj = ResourceManager.GetObject("osk_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_g {
            get {
                object obj = ResourceManager.GetObject("osk_g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_h {
            get {
                object obj = ResourceManager.GetObject("osk_h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_i {
            get {
                object obj = ResourceManager.GetObject("osk_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_j {
            get {
                object obj = ResourceManager.GetObject("osk_j", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_k {
            get {
                object obj = ResourceManager.GetObject("osk_k", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_l {
            get {
                object obj = ResourceManager.GetObject("osk_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_m {
            get {
                object obj = ResourceManager.GetObject("osk_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_n {
            get {
                object obj = ResourceManager.GetObject("osk_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_o {
            get {
                object obj = ResourceManager.GetObject("osk_o", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_OK {
            get {
                object obj = ResourceManager.GetObject("osk_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_p {
            get {
                object obj = ResourceManager.GetObject("osk_p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_q {
            get {
                object obj = ResourceManager.GetObject("osk_q", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_r {
            get {
                object obj = ResourceManager.GetObject("osk_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_s {
            get {
                object obj = ResourceManager.GetObject("osk_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_t {
            get {
                object obj = ResourceManager.GetObject("osk_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_u {
            get {
                object obj = ResourceManager.GetObject("osk_u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_unline {
            get {
                object obj = ResourceManager.GetObject("osk_unline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_v {
            get {
                object obj = ResourceManager.GetObject("osk_v", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_w {
            get {
                object obj = ResourceManager.GetObject("osk_w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_x {
            get {
                object obj = ResourceManager.GetObject("osk_x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_xiegang1 {
            get {
                object obj = ResourceManager.GetObject("osk_xiegang1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_xiegang2 {
            get {
                object obj = ResourceManager.GetObject("osk_xiegang2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_xinghao {
            get {
                object obj = ResourceManager.GetObject("osk_xinghao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_y {
            get {
                object obj = ResourceManager.GetObject("osk_y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap osk_z {
            get {
                object obj = ResourceManager.GetObject("osk_z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap page_login_21 {
            get {
                object obj = ResourceManager.GetObject("page_login_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap page_login_Exit {
            get {
                object obj = ResourceManager.GetObject("page_login_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordIco {
            get {
                object obj = ResourceManager.GetObject("RecordIco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap selected {
            get {
                object obj = ResourceManager.GetObject("selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SelectMeetingMemberBackground {
            get {
                object obj = ResourceManager.GetObject("SelectMeetingMemberBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServerState {
            get {
                object obj = ResourceManager.GetObject("ServerState", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set {
            get {
                object obj = ResourceManager.GetObject("set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap smallBack {
            get {
                object obj = ResourceManager.GetObject("smallBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallTimeControlBackground {
            get {
                object obj = ResourceManager.GetObject("SmallTimeControlBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Style {
            get {
                object obj = ResourceManager.GetObject("Style", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TalkLogBackground {
            get {
                object obj = ResourceManager.GetObject("TalkLogBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TalkLogIco {
            get {
                object obj = ResourceManager.GetObject("TalkLogIco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_m_Ring {
            get {
                object obj = ResourceManager.GetObject("telephone_m_Ring", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_MeetingMemberIsolate {
            get {
                object obj = ResourceManager.GetObject("telephone_MeetingMemberIsolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_MeetingMemberNoSpeek {
            get {
                object obj = ResourceManager.GetObject("telephone_MeetingMemberNoSpeek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_n_Busy {
            get {
                object obj = ResourceManager.GetObject("telephone_n_Busy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_n_Insert {
            get {
                object obj = ResourceManager.GetObject("telephone_n_Insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_n_Keep {
            get {
                object obj = ResourceManager.GetObject("telephone_n_Keep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_n_Listen {
            get {
                object obj = ResourceManager.GetObject("telephone_n_Listen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_n_OffLine {
            get {
                object obj = ResourceManager.GetObject("telephone_n_OffLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_n_OnLine {
            get {
                object obj = ResourceManager.GetObject("telephone_n_OnLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_n_Record {
            get {
                object obj = ResourceManager.GetObject("telephone_n_Record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TellLogDownDown {
            get {
                object obj = ResourceManager.GetObject("TellLogDownDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TellLogDownNormal {
            get {
                object obj = ResourceManager.GetObject("TellLogDownNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TellLogRefreshDown {
            get {
                object obj = ResourceManager.GetObject("TellLogRefreshDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TellLogRefreshNormal {
            get {
                object obj = ResourceManager.GetObject("TellLogRefreshNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TellLogUpDwon {
            get {
                object obj = ResourceManager.GetObject("TellLogUpDwon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TellLogUpNormal {
            get {
                object obj = ResourceManager.GetObject("TellLogUpNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TimeControlBackground {
            get {
                object obj = ResourceManager.GetObject("TimeControlBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopBackGround {
            get {
                object obj = ResourceManager.GetObject("TopBackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopSplit {
            get {
                object obj = ResourceManager.GetObject("TopSplit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WaitIco {
            get {
                object obj = ResourceManager.GetObject("WaitIco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Waiting {
            get {
                object obj = ResourceManager.GetObject("Waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WaitItemBackGound {
            get {
                object obj = ResourceManager.GetObject("WaitItemBackGound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WaitSplit {
            get {
                object obj = ResourceManager.GetObject("WaitSplit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
